# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Post

# Model Form Field configuration
form: $/pmesolution/blog/models/post/fields.yaml

# Model Class name
modelClass: Pmesolution\Blog\Models\Post

# Default redirect location
defaultRedirect: pmesolution/blog/post

# Create page
create:
    title: Create Post
    redirect: pmesolution/blog/post/update/:id
    redirectClose: pmesolution/blog/post

# Update page
update:
    title: Edit Post
    redirect: pmesolution/blog/post
    redirectClose: pmesolution/blog/post

# Preview page
preview:
    title: Preview Post
